version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:15"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/phpunit-bridge
    versions:
    - 5.2.4
    - 5.2.6
  - dependency-name: symfony/property-info
    versions:
    - 5.2.4
  - dependency-name: symfony/flex
    versions:
    - 1.12.2
  - dependency-name: symfony/debug-bundle
    versions:
    - 5.1.11
  - dependency-name: composer/package-versions-deprecated
    versions:
    - 1.11.99.1
  - dependency-name: twig/extra-bundle
    versions:
    - 3.3.0
  - dependency-name: symfony/expression-language
    versions:
    - 5.2.4
